hydra:
  run:
    dir: ./

data_dir: wikidata5m/triplet_text_align_v1.0/logical_circle_once
train_file: ${data_dir}/logic_circle_d3_4_False_s42_v2_25_v1_s42_seq2seq_simple_0_train.json
dev_file: ${data_dir}/logic_circle_d3_4_False_s42_v2_25_v1_s42_seq2seq_simple_0_dev.json
test_file:

# Model
model:
  _target_: models.t5.T5ForSeq2Seq.from_pretrained
  tokenizer: ${model_name_or_path}

# Data loading
read_tensor:
  _target_: data.wikidata5m.text_with_mask.Seq2SeqTextDataset


extended_vocab:

# Data collator
collator:
  _target_: data.wikidata5m.text_with_mask.Seq2SeqTextCollator
  tokenizer: ${model_name_or_path}
  max_input_length: 64
  max_output_length: 128


# Dataloader
num_workers: 4
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: pretrained-models/t5-large-lm-adapt
pretrain:
get_device_map:


output_dir: experiments/t5.large.lm-adapt.logic_circle.gen.v1_v1_seq2seq_simple_v1.64.128.v1.1.w2.A40

do_train: True
evaluate_during_training: True

do_eval: False
eval_sub_path:

do_preprocess: False

# Training hyper-parameters
per_gpu_train_batch_size: 32
per_gpu_eval_batch_size: 32
learning_rate: 5e-4
gradient_accumulation_steps: 32
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.999)"
max_grad_norm: 5.0
num_train_epochs: 1
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

# Optimizer
optimizer: adafactor
use_nvlamb:
bit_training: False


logging_steps: 1
save_best: True
save_steps: -1
eval_steps: 200
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "bleu"
  measure: 1
  best_checkpoint:
  best_result:

generator: True
max_output_length: 128
num_beams: 1
num_return_sequences: 1
output_scores: True
post_process:

# fairscale.FullyShardedDP
fairscale_config:
  _target_: general_util.fsdp_utils.default_initialize
  fp16: ${fp16}
  reshard_after_forward: False
  move_grads_to_cpu: False
  move_params_to_cpu: False

# Deepspeed config
ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [0.9, 0.999]
      eps: ${adam_epsilon}
      weight_decay: ${weight_decay}
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps:
      warmup_max_lr: ${learning_rate}
      warmup_num_steps:
      warmup_type: linear
  gradient_clipping: ${max_grad_norm}
  fp16:
    enabled: ${fp16}
    initial_scale_power: 12
  zero_optimization:
    stage: 3
#    offload_optimizer:
#      device: cpu
#      pin_memory: True
#    offload_param:
#      device: cpu
#      pin_memory: True
#  activation_checkpointing:
#    partition_activations: True
#    cpu_checkpointing: True
#    contiguous_memory_optimization: False
#    number_checkpoints: False
#    synchronize_checkpoint_boundary: False
#    profile: False
  steps_per_print: 1024

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
  outputs_index_or_keys:
#    "train/mlm_loss": mlm_loss
#    "train/cls_loss": cls_loss

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
