hydra:
  run:
    dir: ./

train_file: wiki_erica_path/sampled_data_roberta/train_distant_[1-9].json
dev_file: wiki_erica_path/sampled_data_roberta/train_distant_0.json
test_file: wiki_erica_path/sampled_data_roberta/train_distant_0.json

# Model
model:
  _target_: models.bart.BartDVAE.from_pretrained
  codebook_size: 2048
  code_dim: 32
  vqvae_type: "w_csa_ema"
  commitment_cost: 0.25
  alpha: 1000
  decay: 0.99
  add_norm: False
  detach_extra_outputs: True
  freeze_decoder: True
  mlp_after: True
  add_point_wise: True

# Data loading
read_tensor_train:
  _target_: data.erica_data_readin.ERICASentenceFilterDataset
  cached_path: wiki_erica_path/v9.1/erica_train_1-9_filter.pkl

read_tensor_dev:
  _target_: data.erica_data_readin.ERICASentenceFilterDataset
  cached_path: wiki_erica_path/v9.1/erica_train_0_filter.pkl

read_tensor_test:
  _target_: data.erica_data_readin.ERICASentenceFilterDataset
  cached_path: wiki_erica_path/v9.1/erica_train_0_filter.pkl

extended_vocab: 4

# Data collator
collator:
  _target_: data.erica_data_readin.ERICASentenceCollator
  max_seq_length: 128
  tokenizer: pretrained-models/bart-base
  partial_optim: False
  no_original: False

# Dataloader
num_workers: 4
prefetch_factor: 2

do_preprocess: False

# Wiki path pretrain v8.2
model_name_or_path: pretrained-models/bart-base
pretrain:

#output_dir: experiments/bart.large.vqvae.raw_wiki.v1.0.w4.RTXA6K
#output_dir: experiments/bart.base.vqvae.raw_wiki.v1.0.bottleneck_ema.w2.PA40.lamb
output_dir: experiments/bart.base.vqvae.raw_wiki.v1.2.w_csa_ema.w4.RTXA6K.lamb

do_train: True
evaluate_during_training: True

do_eval: False
eval_sub_path: checkpoint-14000

# Training hyper-parameters
per_gpu_train_batch_size: 128
per_gpu_eval_batch_size: 256
learning_rate: 1e-3
gradient_accumulation_steps: 8
weight_decay: 1e-4
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 5.0
num_train_epochs: 5
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

# Optimizer
optimizer: lamb
use_nvlamb: True
bit_training:


logging_steps: 1
save_best: False
save_steps: 2000
eval_steps: 2000
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:
#  _target_: post_processors.erica_post_processor.ERICAPredictionSaver

#dist_init:
#  _target_: general_util.dist_utils.setup_slurm_distributed


# fairscale.FullyShardedDP
fairscale_config:
#  _target_: general_util.fsdp_utils.recursive_initialize
  _target_: general_util.fsdp_utils.default_initialize
#  _target_: general_util.fsdp_utils.vae_specific_initialize
  fp16: ${fp16}
  move_grads_to_cpu: False
  move_params_to_cpu: False
  flatten_parameters: False

fsdp_config:
  _target_: general_util.torch_fsdp_utils.torch_fsdp_init_decoder_freeze
  fp16: ${fp16}
  fp16_bfloat16: ${fp16_bfloat16}

# Lightseq config
with_lightseq: False

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
  outputs_index_or_keys:
    "train/vq_loss": vq_loss
    "train/commitment_loss": commitment_loss
    "train/mlm_loss": mlm_loss
    "train/z_encoder_mean": z_encoder_mean
    "train/z_decoder_mean": z_decoder_mean

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
