hydra:
  run:
    dir: ./

train_file: wiki_erica_path/v9.1/train_distant.path_v9.1.train.re_id.pkl
dev_file: wiki_erica_path/v9.1/train_distant.path_v9.1.dev.shuffle.re_id.pkl
test_file:

# Model
model:
  _target_: models.vq_vae.RobertaVQVAE.from_pretrained
  seq2seq_path: pretrained-models/bart-base
  quantizer:
    _target_: models.quantizer.CogViewEMAQuantizer
    dim: 768
    n_embed: 512
    decay: 0.98
  embedding_dim: ${model.quantizer.dim}
  input_type: "concat$1"
  z_to_decoder: True
  z_add_top: True

# Data loading
read_tensor:
  _target_: data.erica_data_readin.WikiPathSentenceConditionDataset
  max_seq_length: 128
  cache_path: ${train_file}_{vqa_ema_v1_0}

read_tensor_dev:
  _target_: data.erica_data_readin.WikiPathSentenceConditionDataset
  max_seq_length: 128
  cache_path: ${dev_file}_{vqa_ema_v1_0}

#read_tensor_test:
#  _target_: data.erica_data_readin.WikiPathSentenceConditionDataset
#  max_seq_length: 128

extended_vocab:

# Data collator
collator:
  _target_: data.erica_data_readin.WikiPathSentenceConditionCollator
  enc_tokenizer: pretrained-models/roberta-large
  dec_tokenizer: pretrained-models/bart-base
  max_seq_length: ${read_tensor.max_seq_length}
  reverse: True


# Dataloader
num_workers: 4
prefetch_factor: 2

do_preprocess: False

# Wiki path pretrain v8.2
model_name_or_path: pretrained-models/roberta-large
pretrain:

output_dir: experiments/roberta.large.bart.base.vqvae.ema.wiki_path.c${model.quantizer.n_embed}.v5.2.w8.lamb.RTXA6K

do_train: True
evaluate_during_training: False

do_eval: False
eval_sub_path: checkpoint-25000

# Training hyper-parameters
per_gpu_train_batch_size: 64
per_gpu_eval_batch_size: 256
learning_rate: 5e-5
gradient_accumulation_steps: 1
weight_decay: 1e-4
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 5.0
num_train_epochs: 20
max_steps: 0
warmup_proportion: 0.06
warmup_steps: 0

lr_scheduler: cosine

# Optimizer
optimizer: lamb
use_nvlamb: True
bit_training:


logging_steps: 1
save_best: False
save_steps: 5000
eval_steps: 5000
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "loss"
  measure: -1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:
  _target_: post_processors.erica_post_processor.WikiPathInferencePostProcessor

#dist_init:
#  _target_: general_util.dist_utils.setup_slurm_distributed


# fairscale.FullyShardedDP
fairscale_config:
#  _target_: general_util.fsdp_utils.recursive_initialize
  _target_: general_util.fsdp_utils.default_initialize
#  _target_: general_util.fsdp_utils.vae_specific_initialize
  fp16: ${fp16}
  move_grads_to_cpu: False
  move_params_to_cpu: False
  flatten_parameters: False

fsdp_config:
  _target_: general_util.torch_fsdp_utils.torch_fsdp_init_quantizer_ignore
  fp16: ${fp16}
  fp16_bfloat16: ${fp16_bfloat16}

# Lightseq config
with_lightseq: False

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
  outputs_index_or_keys:
#    "train/vq_loss": vq_loss
    "train/commitment_loss": commitment_loss
    "train/mlm_loss": mlm_loss
    "train/z_encoder_mean": z_encoder_mean
    "train/z_decoder_mean": z_decoder_mean

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
