hydra:
  run:
    dir: ./

aws_output_bucket:

train_file: ../research.data/lima/train.jsonl
test_file: ../research.data/lima/test.jsonl
dist_load_data_barrier: False

# Model
model:
  _target_: transformers.AutoConfig.from_pretrained
  pad_token_id: 0

model_eval:
  _target_: models.llama.LlamaForConditionalGeneration.from_pretrained
  vocab_size: 32005
  torch_dtype:
    _target_: general_util.training_utils.return_torch_dtype
    dtype: float16
  device_map: "auto"
  pad_token_id: 0

get_layers:
    _target_: models.llama_ds_mp_wrap.get_layers_from_config
    activation_checkpointing: True

enable_flash_attention: False

# Pipeline parallelism specific
num_stages: 5
#activation_checkpoint_interval: 1
#pp_loss_fn:
#  _target_: models.llama_ds_mp_wrap.LossFNRatio
#  merit_ratio: 0.9

# Data loading
read_tensor:
  _target_: data.lima.LIMADataset


extended_vocab:

# Data collator

collator:
  _target_: data.collators.flan.CausalLMCollator
  max_seq_length: 2048
  tokenizer: ${model_name_or_path}
  use_fast: False
#  pp_inputs_processor:
#    _target_: data.mp_inputs_process.LlamaPpInputsProcess

# Dataloader
num_workers: 4
prefetch_factor: 2

do_preprocess: False

model_name_or_path: pretrained-models/LLaMA/llama-65b-mp-ext5
#model_name_or_path: pretrained-models/LLaMA/llama-7b-mp4
pretrain:

exp_name: llama.65b.lima.pp8.v1.0.0713
exp_notes:
output_dir: experiments/${exp_name}  # Fix <pad token id>

do_train: True
evaluate_during_training: False

do_eval: False
eval_sub_path: checkpoint-*

# Training hyper-parameters
per_gpu_train_batch_size: 1
per_gpu_eval_batch_size: 1
learning_rate: 1e-5
gradient_accumulation_steps: 32
weight_decay: 0.1
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.99)"
max_grad_norm: 5.0
num_train_epochs: 15
max_steps: -1
warmup_proportion: 0
warmup_steps: 0
total_dataset_len: -1

# Optimizer
optimizer:
use_nvlamb:
bit_training:


logging_steps: 1
#save_best: True
save_best: False
save_steps: 30
eval_steps: -1
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: False

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DefaultForwardFn
post_process:

#dist_init:
#  _target_: general_util.dist_utils.setup_slurm_distributed


# fairscale.FullyShardedDP
fairscale_config:
#  _target_: general_util.fsdp_utils.recursive_initialize
#  _target_: general_util.fsdp_utils.default_initialize
#  _target_: general_util.fsdp_utils.default_initialize_v2
  _target_: general_util.torch_fsdp_utils.torch_fsdp_transformer_init
  fp16: ${fp16}
#  move_grads_to_cpu: False
#  move_params_to_cpu: False
#  flatten_parameters: False
  fp16_bfloat16: ${fp16_bfloat16}
#  disable_reshard_on_root: False


# Deepspeed config
ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [0.9, 0.95]
      eps: ${adam_epsilon}
      weight_decay: ${weight_decay}
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps:
      warmup_max_lr: ${learning_rate}
      warmup_num_steps:
      warmup_type: linear
  gradient_clipping: ${max_grad_norm}
  fp16:
    enabled: true
    loss_scale: 0
    loss_scale_window: 1000
    initial_scale_power: 12
    hysteresis: 2
    min_loss_scale: 1
#  bf16:
#    enabled: ${fp16}
#  autotuning:
#    enabled: true
#    arg_mappings:
#      train_micro_batch_size_per_gpu: "per_gpu_train_batch_size"
#      gradient_accumulation_steps: "gradient_accumulation_steps"
#      zero_optimization: "ds_cfg.zero_optimization"
  zero_optimization:
    stage: 1
    contiguous_gradients: True
    overlap_comm: True
    reduce_scatter: True
    reduce_bucket_size: 5e8
    allgather_partitions: True
    allgather_bucket_size: 5e8
    offload_optimizer:
      device: cpu
      pin_memory: True
#    offload_param:
#      device: cpu
#      pin_memory: True
#  activation_checkpointing:
#    partition_activations: True
#    cpu_checkpointing: True
#    contiguous_memory_optimization: False
#    number_checkpoints: False
#    synchronize_checkpoint_boundary: False
#    profile: False
  steps_per_print: 1

# Lightseq config
with_lightseq: False


summary_helper:
#  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  _target_: general_util.tensorboard_helper.WandbWriter
  batch_index_or_keys:
#    "train/pair_value_num": pair_value_num
#    "train/pair_label_num": pair_label_num
#    "train/dropped_op_cnt": dropped_op_cnt
#    "train/invalid_path": invalid_path
  outputs_index_or_keys:
#    "train/mlm_loss": mlm_loss
#    "train/cls_loss": cls_loss
#    "train/cls_acc": cls_acc
#    "train/tagging_loss": tagging_loss
#    "train/path_gen_loss": path_gen_loss

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
topology:
