hydra:
  run:
    dir: ./

train_file: wiki_erica_path/v9.1/train_distant.path_v9.1.train.re_id.pkl
dev_file: wiki_erica_path/v9.1/train_distant.path_v9.1.dev.shuffle.re_id.pkl
test_file:

# Model
model:
  _target_: models.roberta.RobertaForMultipleChoiceForPreTrainWithPairFullLocal.from_pretrained
  mlp_hidden_size: 2048
  mlm_alpha: 1.0

# Data loading
read_tensor_train:
  _target_: data.wiki_entity_path_v9_1_split_vqvae.convert_examples_into_features_v3_ent_local_pair
  rel_path_set_file: wiki_erica_path/v9.1/pattern_rel_id_kmeans_v21/rel_path_set.train.0.pt
  id2rel_path_decode_id_file: wiki_erica_path/v9.1/pattern_rel_id_kmeans_v21/pattern_decode_id.train.0.c1000.limit0.pkl
  max_neg_num: 3
  aug_num: 1
  max_seq_length: 512
  shuffle_context: True
  min_rep_num: 5
  geo_p: 0.4
  deduct_ratio: 1.0
  context_ratio: 1.0
  noise_sent_ratio: 0.0
  num_workers: 48

read_tensor_dev:
  _target_: data.wiki_entity_path_v9_1_split_vqvae.convert_examples_into_features_v3_ent_local_pair
  rel_path_set_file: wiki_erica_path/v9.1/pattern_rel_id_kmeans_v21/rel_path_set.dev.shuffle.pt
  id2rel_path_decode_id_file: wiki_erica_path/v9.1/pattern_rel_id_kmeans_v21/pattern_decode_id.dev.shuffle.c1000.limit0.pkl
  max_neg_num: 3
  aug_num: 1
  max_seq_length: 512
  shuffle_context: True
  min_rep_num: 5
  geo_p: 0.4
  deduct_ratio: 1.0
  context_ratio: 1.0
  noise_sent_ratio: 0.0
  num_workers: 48

extended_vocab:

# Data collator
collator:
  _target_: data.collators.wiki.WikiPathDatasetCollatorWithContextAndPairCompleteKMeansLocal
  max_seq_length: 512
  tokenizer: pretrained-models/roberta-large
  mlm_probability: 0.15
  max_option_num: 4
  swap: True
  option_dropout: 0.5

# Dataloader
num_workers: 8
prefetch_factor: 2

do_preprocess: False

# Wiki path pretrain v8.2
model_name_or_path: pretrained-models/roberta-large
pretrain:

output_dir: experiments/roberta.large.wiki_erica_path_v9.1_v9.1.pair.kmeans.local.v2.1.1aug.seq512.w8.lamb.500steps.RTXA6K

do_train: True
evaluate_during_training: True

do_eval: False
eval_sub_path:

# Training hyper-parameters
per_gpu_train_batch_size: 8
per_gpu_eval_batch_size: 16
learning_rate: 5e-5
gradient_accumulation_steps: 256
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 5.0
num_train_epochs: 10
max_steps: 500
warmup_proportion: 0.1
warmup_steps: 0

# Optimizer
optimizer: lamb
use_nvlamb: True
bit_training:


logging_steps: 1
save_best: False
save_steps: 100
eval_steps: 100
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:
eval_forward_fn:
  _target_: general_util.evaluator.DiscriminatorForwardFn
post_process:

#dist_init:
#  _target_: general_util.dist_utils.setup_slurm_distributed


# fairscale.FullyShardedDP
fairscale_config:
#  _target_: general_util.fsdp_utils.recursive_initialize
  _target_: general_util.fsdp_utils.default_initialize
  fp16: ${fp16}
  move_grads_to_cpu: False
  move_params_to_cpu: False

# Lightseq config
with_lightseq: False

# Deepspeed config
ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [0.9, 0.999]
      eps: ${adam_epsilon}
      weight_decay: ${weight_decay}
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps:
      warmup_max_lr: ${learning_rate}
      warmup_num_steps:
      warmup_type: linear
  gradient_clipping: ${max_grad_norm}
  fp16:
    enabled: ${fp16}
    initial_scale_power: 12
  zero_optimization:
    stage: 3
#    offload_optimizer:
#      device: cpu
#      pin_memory: True
#    offload_param:
#      device: cpu
#      pin_memory: True
#  activation_checkpointing:
#    partition_activations: True
#    cpu_checkpointing: True
#    contiguous_memory_optimization: False
#    number_checkpoints: False
#    synchronize_checkpoint_boundary: False
#    profile: False
  steps_per_print: 1024

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
    "train/pair_value_num": pair_value_num
    "train/pair_label_num": pair_label_num
    "train/dropped_op_cnt": dropped_op_cnt
  outputs_index_or_keys:
    "train/mlm_loss": mlm_loss
    "train/cls_loss": cls_loss
    "train/pair_loss": pair_loss
    "train/local_ctr_loss": local_ctr_loss

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
