# model
model_name_or_path: 'pretrained-models/LLaMA/llama-7b'
# data
dataset_name: 'wic'
refresh: false
data_tag: 'base'
train_on_inputs: false
data_max_length: 1024
# training
# trainer
tag: 'lomo'
output_dir: 'experiments/llama.65b.merit_v91_v91.seq2seq.v5.4.3aug.w6.adamw.500steps.NA100.0605.lomo'
overwrite_output_dir: true
deepspeed: 'lomo/config/ds_config.json'
do_train: true
#do_eval: true
do_eval: false
#evaluation_strategy: 'epoch'
evaluation_strategy: "no"
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 512
learning_rate: 1e-6
weight_decay: 0
num_train_epochs: 1
lr_scheduler_type: 'linear'
warmup: 0.01
clip_grad_norm: 1.0
save_strategy: 'steps'
save_steps: 50
save_total_limit: 0
seed: 42
bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: false