hydra:
  run:
    dir: ./

data_dir: wikidata5m/triplet_text_align_v1.0/logical_circle_once
train_file: ${data_dir}/logic_circle_d3_4_False_s42_v2_25_v1_s42_mlm_simple_roberta_train.json
dev_file: ${data_dir}/logic_circle_d3_4_False_s42_v2_25_v1_s42_mlm_simple_roberta_dev.json
test_file:

# Model
model:
  _target_: models.roberta.RobertaForMaskedLM.from_pretrained

# Data loading
read_tensor:
  _target_: data.wikidata5m.text_with_mask.MLMTextDataset


extended_vocab:

# Data collator
collator:
  _target_: data.wikidata5m.text_with_mask.MLMTextCollator
  tokenizer: ${model_name_or_path}
  max_seq_length: 384
  mlm_probability: 0.15
  span_mlm_probability: 0.4
  span_min_predictions: 2


# Dataloader
num_workers: 4
prefetch_factor: 2

# Wiki path pretrain v8.2
model_name_or_path: pretrained-models/roberta-large
pretrain:
get_device_map:


output_dir: experiments/roberta.large.logic_circle.v1_v1_mlm_simple_v1.v1.2.384.w4.RTX6000

do_train: True
evaluate_during_training: True

do_eval: False
eval_sub_path:

do_preprocess: False

# Training hyper-parameters
per_gpu_train_batch_size: 8
per_gpu_eval_batch_size: 8
learning_rate: 5e-4
gradient_accumulation_steps: 128
weight_decay: 0.01
adam_epsilon: 1e-6
adam_betas: "(0.9, 0.98)"
max_grad_norm: 5.0
num_train_epochs: 5
max_steps: 0
warmup_proportion: 0.1
warmup_steps: 0

# Optimizer
optimizer:
use_nvlamb:
bit_training: False


logging_steps: 1
save_best: True
save_steps: 500
eval_steps: 300
ddp_eval: True
no_cuda: False
seed: 42
local_rank: -1
fp16: True
fp16_opt_level: O1
fp16_bfloat16: True

# Prediction config
prediction_cfg:
  metric: "acc"
  measure: 1
  best_checkpoint:
  best_result:

generator: False
eval_forward_fn:
  _target_: general_util.evaluator.DiscriminatorForwardFn
post_process:

dist_init:
  _target_: general_util.dist_utils.setup_slurm_distributed

# fairscale.FullyShardedDP
fairscale_config:
  _target_: general_util.fsdp_utils.default_initialize
  fp16: ${fp16}
  reshard_after_forward: False
  move_grads_to_cpu: False
  move_params_to_cpu: False

# Deepspeed config
ds_cfg:
  train_micro_batch_size_per_gpu: ${per_gpu_train_batch_size}
  gradient_accumulation_steps: ${gradient_accumulation_steps}
  optimizer:
    type: AdamW
    params:
      lr: ${learning_rate}
      betas: [0.9, 0.999]
      eps: ${adam_epsilon}
      weight_decay: ${weight_decay}
  scheduler:
    type: WarmupDecayLR
    params:
      total_num_steps:
      warmup_max_lr: ${learning_rate}
      warmup_num_steps:
      warmup_type: linear
  gradient_clipping: ${max_grad_norm}
  fp16:
    enabled: ${fp16}
    initial_scale_power: 12
  zero_optimization:
    stage: 3
#    offload_optimizer:
#      device: cpu
#      pin_memory: True
#    offload_param:
#      device: cpu
#      pin_memory: True
#  activation_checkpointing:
#    partition_activations: True
#    cpu_checkpointing: True
#    contiguous_memory_optimization: False
#    number_checkpoints: False
#    synchronize_checkpoint_boundary: False
#    profile: False
  steps_per_print: 1024

summary_helper:
  _target_: general_util.tensorboard_helper.SummaryWriterHelper
  batch_index_or_keys:
  outputs_index_or_keys:
#    "train/mlm_loss": mlm_loss
#    "train/cls_loss": cls_loss

# Temporary variables
n_gpu:
device:
train_batch_size:
eval_batch_size:
world_size:
